# Generated by Django 3.1.2 on 2020-10-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
