# Generated by Django 3.1.2 on 2020-10-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0003_auto_20201028_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='weight',
            field=models.FloatField(),
        ),
    ]
