# Generated by Django 3.1.2 on 2020-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0004_auto_20201028_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
